version: "3.3"
services:
  web:
    build:
      context: client/
      dockerfile: Dockerfile-production
    environment:
      - GRAPHQL_ENDPOINT=graphql
      - NODE_ENV=production
    volumes:
      - "./client/:/app"
      - "/app/node_modules"
    ports:
      - "80:80"

  minio:
    image: minio/minio:RELEASE.2019-08-07T01-59-21Z
    volumes:
      - minio_data:/data:rw
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      MINIO_DOMAIN: dashboard.jeffhq.com
    command: server /data

  # createbuckets:
  #   image: minio/mc
  #   depends_on:
  #     - minio
  #   entrypoint: >
  #     /bin/sh -c "
  #     /usr/bin/mc config host add myminio http://minio:9000 minio minio123;
  #     /usr/bin/mc rm -r --force myminio/sat-images;
  #     /usr/bin/mc mb myminio/sat-images;
  #     /usr/bin/mc policy --insecure set public myminio/sat-images;
  #     exit 0;
  #     "

  database:
    image: postgres:latest
    environment:
      - PG_TRUST_LOCALNET=true
      - POSTGRES_USER=dashboard
      - POSTGRES_PASSWORD=dashboard
      - POSTGRES_DB=dashboard
    ports:
      - "5500:5432"
    volumes:
      - dashboard-data:/var/lib/postgresql/data

  graphql:
    image: hasura/graphql-engine:v1.0.0-beta.10
    ports:
      - "8080:8080"
    depends_on:
      - "database"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://dashboard:dashboard@database:5432/dashboard
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey

  redis:
    image: redis:alpine
    ports:
      - 6379
    volumes:
      - ./redis:/data

volumes:
  dashboard-data:
    driver: local
  minio_data:
    driver: local
