name: Remote Deployment

on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script_stop: true
          script: |
            # Clone repo if not already here
            if [ ! -d "dashboard" ]; then
              git clone https://${{ secrets.GHUB_PTOKEN }}@github.com/jhodges10/dashboard.git
              # Control will enter here if $DIRECTORY doesn't exist.
            fi
              # Change directory to inside the repo
              cd dashboard
              git pull
              git checkout master

              # Build and deploy
              make rebuild
